<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Two-Factor Authentication - {{ config('app.name', 'HotelTV') }}</title>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- FontAwesome icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    
    <style>
        body {
            font-family: 'Outfit', sans-serif;
            background: linear-gradient(135deg, #0f172a 0%, #1e1b4b 50%, #0f172a 100%);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            color: #f8fafc;
        }

        .auth-card {
            background: rgba(30, 41, 59, 0.85);
            backdrop-filter: blur(16px);
            border: 1px solid rgba(255, 255, 255, 0.1);
            border-radius: 24px;
            box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5);
            width: 100%;
            max-width: 440px;
            padding: 40px 32px;
        }

        .otp-inputs {
            display: flex;
            gap: 10px;
            justify-content: center;
            margin: 24px 0;
        }

        .otp-field {
            width: 48px;
            height: 56px;
            border-radius: 12px;
            border: 2px solid rgba(255, 255, 255, 0.15);
            background: rgba(15, 23, 42, 0.6);
            color: #ffffff;
            font-size: 24px;
            font-weight: 700;
            text-align: center;
            transition: all 0.2s ease;
        }

        .otp-field:focus {
            border-color: #6366f1;
            box-shadow: 0 0 15px rgba(99, 102, 241, 0.4);
            background: rgba(15, 23, 42, 0.9);
            outline: none;
        }

        .btn-primary-custom {
            background: linear-gradient(135deg, #6366f1 0%, #4f46e5 100%);
            border: none;
            border-radius: 14px;
            padding: 14px;
            font-weight: 600;
            font-size: 16px;
            color: #ffffff;
            width: 100%;
            transition: all 0.2s ease;
        }

        .btn-primary-custom:hover {
            transform: translateY(-2px);
            box-shadow: 0 8px 20px rgba(99, 102, 241, 0.4);
        }

        .toggle-mode {
            color: #94a3b8;
            font-size: 14px;
            cursor: pointer;
            text-decoration: underline;
        }
        .toggle-mode:hover {
            color: #cbd5e1;
        }
    </style>
</head>
<body>

<div class="auth-card text-center">
    <div class="mb-4">
        <div class="d-inline-flex align-items-center justify-content-center bg-primary bg-opacity-10 text-primary rounded-circle" style="width: 72px; height: 72px;">
            <i class="fa-solid fa-shield-halved fa-2x"></i>
        </div>
    </div>

    <h4 class="fw-bold mb-2">Two-Step Verification</h4>
    <p class="text-secondary small mb-4">Enter the 6-digit verification code generated by your Authenticator app to continue.</p>

    @if ($errors->any())
        <div class="alert alert-danger border-0 rounded-3 text-start small mb-3">
            <ul class="mb-0 ps-3">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('2fa.verify') }}" method="POST" id="verifyForm">
        @csrf
        <input type="hidden" name="one_time_password" id="otpValue">

        <!-- TOTP Mode -->
        <div id="totpSection">
            <div class="otp-inputs" id="otpInputs">
                <input type="text" maxlength="1" class="otp-field" autofocus>
                <input type="text" maxlength="1" class="otp-field">
                <input type="text" maxlength="1" class="otp-field">
                <input type="text" maxlength="1" class="otp-field">
                <input type="text" maxlength="1" class="otp-field">
                <input type="text" maxlength="1" class="otp-field">
            </div>
            <div class="mt-3">
                <span class="toggle-mode" onclick="toggleRecoveryMode(true)">Use an emergency recovery code</span>
            </div>
        </div>

        <!-- Recovery Code Mode -->
        <div id="recoverySection" style="display: none;">
            <div class="my-3">
                <input type="text" id="recoveryCodeInput" class="form-control form-control-lg text-center bg-dark text-white border-secondary rounded-3" placeholder="Enter emergency code (e.g. xxxxx-xxxxx)">
            </div>
            <div class="mt-2 mb-3">
                <span class="toggle-mode" onclick="toggleRecoveryMode(false)">Use 6-digit Authenticator code</span>
            </div>
        </div>

        <button type="submit" class="btn btn-primary-custom mt-3">
            <i class="fa-solid fa-lock-open me-2"></i> Verify & Access Account
        </button>
    </form>
</div>

<script>
    const fields = document.querySelectorAll('.otp-field');
    const otpValueInput = document.getElementById('otpValue');
    const form = document.getElementById('verifyForm');
    let isRecoveryMode = false;

    fields.forEach((field, index) => {
        field.addEventListener('input', (e) => {
            if (e.target.value.length === 1 && index < fields.length - 1) {
                fields[index + 1].focus();
            }
            updateOtpValue();
        });

        field.addEventListener('keydown', (e) => {
            if (e.key === 'Backspace' && !field.value && index > 0) {
                fields[index - 1].focus();
            }
        });

        field.addEventListener('paste', (e) => {
            e.preventDefault();
            const data = (e.clipboardData || window.clipboardData).getData('text').trim();
            if (data.length === 6 && /^\d+$/.test(data)) {
                data.split('').forEach((char, i) => {
                    if (fields[i]) fields[i].value = char;
                });
                updateOtpValue();
                fields[5].focus();
            }
        });
    });

    function updateOtpValue() {
        if (!isRecoveryMode) {
            let code = '';
            fields.forEach(f => code += f.value);
            otpValueInput.value = code;
        }
    }

    function toggleRecoveryMode(enable) {
        isRecoveryMode = enable;
        document.getElementById('totpSection').style.display = enable ? 'none' : 'block';
        document.getElementById('recoverySection').style.display = enable ? 'block' : 'none';
        
        if (enable) {
            document.getElementById('recoveryCodeInput').focus();
        } else {
            fields[0].focus();
        }
    }

    form.addEventListener('submit', (e) => {
        if (isRecoveryMode) {
            otpValueInput.value = document.getElementById('recoveryCodeInput').value.trim();
        } else {
            updateOtpValue();
        }
    });
</script>

</body>
</html>
